# System-level sops secrets (NixOS).
#
# Mirrors modules/common/sops.nix (the Home Manager variant) but for NixOS
# secrets that need to exist before user-login — e.g. the LiteLLM container's
# API keys, read by systemd services running as root.
#
# Decrypted secrets land under /run/secrets/<name> with mode 0400, owned by root.
{...}: {
  sops = {
    age.keyFile = "/home/killua/.config/sops/age/keys.txt";
    defaultSopsFile = ../../secrets/personal.yaml;
    secrets = {
      nvidia_api_key = {};
      google_studio_key = {};
      mistral_api_key = {};
      mistral_codestral_api_key = {};
      icloud_email = {};
      # SearXNG settings.yml secret_key — substituted into the container's
      # settings.yml at start via the SEARXNG_SECRET env var. Generate with
      # `openssl rand -hex 32`.
      searxng_secret_key = {};
      # Karakeep — NextAuth session signing key (32+ bytes hex).
      # Generate with: openssl rand -hex 32
      karakeep_nextauth_secret = {};
      # Meilisearch master key — required by meili in production mode and
      # shared with the karakeep web container so it can authenticate.
      # Generate with: openssl rand -hex 32
      karakeep_meili_master_key = {};
      karakeep_openai_api_key = {};
      # Admin user seeded by karakeep-bootstrap.service on the very first
      # boot against an empty data volume. The bootstrap is sentinel-gated, so
      # rotating these here will NOT change the running admin password — wipe
      # the karakeep_data volume to re-seed, or change the password via the UI.
      karakeep_admin_email = {};
      karakeep_admin_password = {};
      # API key generated by the admin in Karakeep UI (Settings → API Keys).
      # Without this the import service can't authenticate, so it bails
      # gracefully — populate this key after the first successful bootstrap.
      karakeep_admin_api_key = {};
      # Netscape-format HTML bookmark export, kept encrypted under sops.
      # karakeep-import.service decrypts + parses it on boot and on the
      # daily timer. Replace the file in-place (`sops secrets/karakeep-bookmarks.html`)
      # to push a new set of bookmarks; the importer is idempotent (Karakeep
      # dedupes by URL), so re-imports are safe.
      karakeep_bookmarks_html = {
        sopsFile = ../../secrets/karakeep-bookmarks.html;
        format = "binary";
      };

      # FreshRSS — admin login + Google Reader API password (used by NewsFlash
      # desktop client). Seeded on first boot via ADMIN_* env vars; rotating
      # these here does NOT change the running passwords (wipe freshrss_data
      # volume to re-seed, or change in the FreshRSS UI under Configuration →
      # Authentication / Profile).
      freshrss_admin_password = {};
      freshrss_admin_api_password = {};
      # Note: `freshrss_opml` is NOT declared here. opml.nix declares it
      # conditionally on `cfg.useSops = true` so users running drop-folder-only
      # don't need the secret in personal.yaml.

      # ── Glance dashboard env-file (modules/containers/glance.nix) ──
      # Assembled into /run/glance/env by glance-env.service and consumed by
      # the glance container via EnvironmentFile. Glance expands ${VAR} in
      # glance.yml at startup. Karakeep reuses the existing
      # karakeep_admin_api_key declared above — no duplicate sops entry.
      # Cronicle API key not wired (uses admin/admin session login).
      #
      # GitHub fine-grained PAT — raises the `releases` widget above
      # GitHub's 60 req/h anonymous cap. Scope: "Public Repositories
      # (read-only)" is sufficient (Metadata: Read + Contents: Read).
      glance_github_token = {};
      # Google Calendar private iCal URL — calendar.google.com → Settings →
      # your calendar → "Secret address in iCal format". Treat as a secret;
      # anyone with the URL can read every event on the calendar.
      glance_gcal_ical_url = {};

      # Speedtest Tracker (modules/containers/speedtest-tracker.nix).
      # APP_KEY: Laravel encryption key. `openssl rand -base64 32`. MUST be set
      # before first boot and never rotated (would invalidate stored history).
      speedtest_tracker_app_key = {};
      # API token: generated in the UI after first boot (Settings → API tokens).
      # Read by glance-env.service into the glance container as
      # ${SPEEDTEST_TRACKER_API_TOKEN}.
      speedtest_tracker_api_token = {};

      # Trakt.tv + TMDB — drive the Home-page media widgets in glance.
      # `trakt_api_key`     = the Trakt OAuth app's Client ID
      #                       (https://trakt.tv/oauth/applications). Public
      #                       endpoints (trending) need only this.
      # `trakt_access_token`= OAuth Bearer token for /calendars/my/...
      #                       Obtained via `scripts/trakt-auth.sh` device flow.
      #                       Expires after ~3 months — re-run the script + sops
      #                       to rotate. No automated refresh.
      # `trakt_username`    = Trakt username (plaintext, used in history URL).
      # `tmdb_api_key`      = themoviedb.org v3 API key. Used by glance's
      #                       custom-api templates to enrich Trakt entries
      #                       with poster art.
      trakt_api_key = {};
      trakt_access_token = {};
      trakt_username = {};
      tmdb_api_key = {};

      # ── Matrix stack (modules/containers/matrix) ──
      # Postgres superuser + per-service role passwords.
      matrix_postgres_password = {};
      matrix_synapse_db_password = {};
      # Synapse-side appservice/registration secret. Anyone holding this can
      # mint user accounts via the admin API.
      matrix_synapse_registration_secret = {};

      # Per-bridge: db_password / as_token / hs_token / pickle_key.
      # Tokens are 32-byte hex strings shared between the bridge's config and
      # the synapse-side registration file — they prove appservice identity.
      # pickle_key is the local key used by the bridge to encrypt its own
      # E2EE session state; rotating it nukes encrypted history for that bridge.
      matrix_bridge_telegram_db_password = {};
      matrix_bridge_telegram_as_token = {};
      matrix_bridge_telegram_hs_token = {};
      matrix_bridge_telegram_pickle_key = {};
      # Telegram-only: app credentials from https://my.telegram.org → API development tools.
      matrix_bridge_telegram_api_id = {};
      matrix_bridge_telegram_api_hash = {};

      matrix_bridge_whatsapp_db_password = {};
      matrix_bridge_whatsapp_as_token = {};
      matrix_bridge_whatsapp_hs_token = {};
      matrix_bridge_whatsapp_pickle_key = {};

      matrix_bridge_meta_instagram_db_password = {};
      matrix_bridge_meta_instagram_as_token = {};
      matrix_bridge_meta_instagram_hs_token = {};
      matrix_bridge_meta_instagram_pickle_key = {};

      matrix_bridge_meta_messenger_db_password = {};
      matrix_bridge_meta_messenger_as_token = {};
      matrix_bridge_meta_messenger_hs_token = {};
      matrix_bridge_meta_messenger_pickle_key = {};
    };
  };
}
