{ lib, ... }: {
  wayland.windowManager.hyprland.settings = {
    bindd = [
    "Super, Period, Emoji >> clipboard, global, quickshell:overviewEmojiToggle"
    "Super, A, Toggle left sidebar, global, quickshell:sidebarLeftToggle"
    "Super, Slash, Toggle cheatsheet, global, quickshell:cheatsheetToggle"
    "Super, M, Toggle media controls, global, quickshell:mediaControlsToggle"
    "Ctrl+Alt, Delete, Toggle session menu, global, quickshell:sessionToggle"
    "Super, J, Toggle bar, global, quickshell:barToggle"
    "Ctrl+Super, T, Toggle wallpaper selector, global, quickshell:wallpaperSelectorToggle"
    "Super+Shift, T, Character recognition,exec, uwsm-app --grim -g '$(slurp $SLURP_ARGS)' 'tmp.png' && tesseract 'tmp.png' - | wl-copy && rm 'tmp.png'"
    "Super, L, Lock, exec, uwsm-app -- dms ipc call lock lock"
    "Ctrl+Shift+Alt+Super, Delete, Shutdown, exec, uwsm-app -- systemctl poweroff || loginctl poweroff"
    ];
    bind = [
    "Super+Alt, A, global, quickshell:sidebarLeftToggleDetach"
    "Super, B, global, quickshell:sidebarLeftToggle"
    "Ctrl+Super, R, exec,killall ags agsv1 gjs ydotool qs quickshell; dms restart &"
    ", Print, exec,sh -c 'REGION=$(slurp) || exit; grim -g \"$REGION\" - | satty -f -'"
    "Super, Left, movefocus, l"
    "Super, Right, movefocus, r"
    "Super, Up, movefocus, u"
    "Super, Down, movefocus, d"
    "Super, BracketLeft, movefocus, l"
    "Super, BracketRight, movefocus, r"
    "Super+Shift, Left, movewindow, l"
    "Super+Shift, Right, movewindow, r"
    "Super+Shift, Up, movewindow, u"
    "Super+Shift, Down, movewindow, d"
    "Alt, F4, killactive,"
    "Super, Q, killactive,"
    "Super Shift, C, killactive,"
    "Super+Shift+Alt, Q, exec, uwsm-app -- hyprctl kill"
    "Super+Alt, Space, togglefloating, "
"Super, D, fullscreen, 1 "
"Super+Shift, F, fullscreen, 0 "
"Super, F, scroller:cyclewidth, next"
"Super+Alt, F, fullscreenstate, 0 3 "
"Super, P, pin "
"Super+Shift, mouse_down, movetoworkspace, r-1 "
"Super+Shift, mouse_up, movetoworkspace, r+1 "
"Super+Alt, mouse_down, movetoworkspace, -1 "
"Super+Alt, mouse_up, movetoworkspace, +1 "
"Super+Alt, Page_Down, movetoworkspace, +1 "
"Super+Alt, Page_Up, movetoworkspace, -1 "
"Super+Shift, Page_Down, movetoworkspace, r+1  "
"Super+Shift, Page_Up, movetoworkspace, r-1  "
"Ctrl+Super+Shift, Right, movetoworkspace, r+1 "
"Ctrl+Super+Shift, Left, movetoworkspace, r-1 "
"Super+Alt, S, movetoworkspacesilent, special "
"Ctrl+Super, S, togglespecialworkspace, "
"Alt, Tab, cyclenext "
"Alt, Tab, bringactivetotop, "
"ALT Shift, Tab, cyclenext, prev"
"ALT Shift, Tab, bringactivetotop,"
"Super, 1, workspace, 1"
"Super, 2, workspace, 2"
"Super, 3, workspace, 3"
"Super, 4, workspace, 4"
"Super, 5, workspace, 5"
"Super, 6, workspace, 6"
"Super, 7, workspace, 7"
"Super, 8, workspace, 8"
"Super, 9, workspace, 9"
"Super, 0, workspace, 10"
"Ctrl+Super, Right, workspace, r+1 "
"Ctrl+Super, Left, workspace, r-1 "
"Ctrl+Super+Alt, Right, workspace, m+1 "
"Ctrl+Super+Alt, Left, workspace, m-1 "
"Super, Page_Down, workspace, +1 "
"Super, Page_Up, workspace, -1 "
"Ctrl+Super, Page_Down, workspace, r+1 "
"Ctrl+Super, Page_Up, workspace, r-1 "
"Super, mouse_up, workspace, +1 "
"Super, mouse_down, workspace, -1 "
"Ctrl+Super, mouse_up, workspace, r+1 "
"Ctrl+Super, mouse_down, workspace, r-1 "
"Super, S, togglespecialworkspace, "
"Super, mouse:275, togglespecialworkspace, "
"Ctrl+Super, BracketLeft, workspace, -1 "
"Ctrl+Super, BracketRight, workspace, +1 "
"Ctrl+Super, Up, workspace, r-5 "
"Ctrl+Super, Down, workspace, r+5 "
"Super, Return, exec, uwsm-app -- kitty"
"Ctrl+Super, Backslash, resizeactive, exact 640 480 "
"Super, W, exec, vicinae toggle"
"Super, V, exec, vicinae vicinae://extensions/vicinae/clipboard/history"
"Super, TAB,workspace,previous"
"Super, N, movefocus, l"
"Super, O, movefocus, r"
"Super, I, movefocus, u"
"Super, E, movefocus, d"
"Super SHIFT, N, movewindow, l"
"Super SHIFT, O, movewindow, r"
"Super SHIFT, I, movewindow, u"
"Super, U, exec, uuctl"
"Super SHIFT, E, movewindow, d"
"Super SHIFT, 1, movetoworkspace, 1"
"Super SHIFT, 2, movetoworkspace, 2"
"Super SHIFT, 3, movetoworkspace, 3"
"Super SHIFT, 4, movetoworkspace, 4"
"Super SHIFT, 5, movetoworkspace, 5"
"Super SHIFT, 6, movetoworkspace, 6"
"Super SHIFT, 7, movetoworkspace, 7"
"Super SHIFT, 8, movetoworkspace, 8"
"Super SHIFT, 9, movetoworkspace, 9"
"Super SHIFT, 0, movetoworkspace, 10"
"Super, F12, exec, uwsm-app -- /home/killua/.local/bin/switch-session.sh"
"Super , T, togglefloating,"
"Super ALT, L, exec, uwsm-app -- dms ipc call lock lock"
"Super+Shift+Alt, mouse:275, exec, uwsm-app -- playerctl previous" # [hidden]
"Super+Shift+Alt, mouse:276, exec, uwsm-app -- playerctl next || playerctl position `bc <<< '100 * $(playerctl metadata mpris:length) / 1000000 / 100'`" # [hidden]
    ];
    bindle = [
    ", XF86AudioRaiseVolume, exec, uwsm-app -- wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+"
    ", XF86AudioLowerVolume, exec, uwsm-app -- wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"
    ];
    bindel = [
      ", XF86KbdBrightnessUp, exec, kbdbrite.sh up"
      ", XF86KbdBrightnessDown, exec, kbdbrite.sh down"
      ", XF86MonBrightnessUp, exec, dms ipc call brightness increment 5"
      ", XF86MonBrightnessDown, exec, dms ipc call brightness decrement 5"
      ", XF86AudioRaiseVolume, exec, dms ipc call audio increment 3"
      ", XF86AudioLowerVolume, exec, dms ipc call audio decrement 3"
    ];
    bindl = [
    ",XF86AudioMute, exec, uwsm-app -- wpctl set-mute @DEFAULT_SINK@ toggle"
    "Alt ,XF86AudioMute, exec, uwsm-app -- wpctl set-mute @DEFAULT_SOURCE@ toggle"
    ",XF86AudioMicMute, exec, uwsm-app -- wpctl set-mute @DEFAULT_SOURCE@ toggle"
    "Super+Shift, N, exec, uwsm-app -- playerctl next || playerctl position `bc <<< '100 * $(playerctl metadata mpris:length) / 1000000 / 100'`"
    ",XF86AudioNext, exec, uwsm-app -- playerctl next || playerctl position `bc <<< '100 * $(playerctl metadata mpris:length) / 1000000 / 100'`"
    ",XF86AudioPrev, exec, uwsm-app -- playerctl previous "
    "Super+Shift, B, exec, uwsm-app -- playerctl previous "
    "Super+Shift, P, exec, uwsm-app -- playerctl play-pause "
    ",XF86AudioPlay, exec, uwsm-app -- playerctl play-pause "
    ",XF86AudioPause, exec, uwsm-app -- playerctl play-pause "
    ", XF86AudioMute, exec, dms ipc call audio mute"
    ", XF86AudioMicMute, exec, dms ipc call audio micmute"
    ];
    bindld = [
    "Super+Shift,M, Toggle mute, exec, uwsm-app -- wpctl set-mute @DEFAULT_SINK@ toggle"
    "Super+Alt,M, Toggle mic, exec, uwsm-app -- wpctl set-mute @DEFAULT_SOURCE@ toggle"
    "Super+Shift, L, Suspend system, exec, uwsm-app -- systemctl suspend || loginctl suspend"
    ];
    bindm = [
    "Super, mouse:272, movewindow"
    "Super, mouse:274, movewindow"
    "Super, mouse:273, resizewindow"
    ];

    binde = [
"Super, Semicolon, splitratio, -0.1" # [hidden]
"Super, Apostrophe, splitratio, +0.1" # [hidden]
    ];
    };
  }
