{ lib, ... }: {

  wayland.windowManager.hyprland.settings = {
    windowrule = [
      "border_color rgba(006591AA) rgba(00659177),match:pin 1"
      "float 1, match:class blueman-manager"
      "pin 1, match:class blueman-manager"
      "float 1, match:class firefox-nightly, match:title Picture-in-Picture"
      "size 800 450, match:class firefox-nightly, match:title Picture-in-Picture"
      "pin 1, match:class firefox-nightly, match:title Picture-in-Picture"
      "float 1, match:class ^(org.gnome.NautilusPreviewer)$"
      "no_blur 1,match:class ^()$,match:title  ^()$"
      "center 1, match:title  ^(Open File)(.*)$"
      "float 1, match:title  ^(Open File)(.*)$"
      "center 1, match:title  ^(Select a File)(.*)$"
      "float 1, match:title  ^(Select a File)(.*)$"
      "center 1, match:title  ^(Choose wallpaper)(.*)$"
      "float 1, match:title  ^(Choose wallpaper)(.*)$"
      "size 60% 65%, match:title  ^(Choose wallpaper)(.*)$"
      "center 1, match:title  ^(Open Folder)(.*)$"
      "float 1, match:title  ^(Open Folder)(.*)$"
      "center 1, match:title  ^(Save As)(.*)$"
      "float 1, match:title  ^(Save As)(.*)$"
      "center 1, match:title  ^(Library)(.*)$"
      "float 1, match:title  ^(Library)(.*)$"
      "center 1, match:title  ^(File Upload)(.*)$"
      "float 1, match:title  ^(File Upload)(.*)$"
      "center 1, match:title  ^(.*)(wants to save)$"
      "float 1, match:title  ^(.*)(wants to save)$"
      "center 1, match:title  ^(.*)(wants to open)$"
      "float 1, match:title  ^(.*)(wants to open)$"
      "float 1, match:class ^(blueberry\\.py)$"
      "float 1, match:class ^(guifetch)$   # FlafyDev/guifetch"
      "float 1, match:class ^(pavucontrol)$"
      "size 45%, match:class ^(pavucontrol)$"
      "center 1, match:class ^(pavucontrol)$"
      "float 1, match:class ^(org.pulseaudio.pavucontrol)$"
      "size 45%, match:class ^(org.pulseaudio.pavucontrol)$"
      "center 1, match:class ^(org.pulseaudio.pavucontrol)$"
      "float 1, match:class ^(nm-connection-editor)$"
      "size 45%, match:class ^(nm-connection-editor)$"
      "center `, match:class ^(nm-connection-editor)$"
      "float 1, match:class .*plasmawindowed.*"
      "float 1, match:class kcm_.*"
      "float 1, match:class .*bluedevilwizard"
      "float 1, match:title  .*Welcome"
      "float 1, match:title  ^(illogical-impulse Settings)$"
      "float 1, match:title  .*Shell conflicts.*"
      "float 1, match:class org.freedesktop.impl.portal.desktop.kde"
      "size 60% 65%, match:class org.freedesktop.impl.portal.desktop.kde"
      "float 1, match:class ^(Zotero)$"
      "size 45%, match:class ^(Zotero)$"
      "float 1, match:class ^(plasma-changeicons)$"
      "no_initial_focus 1, match:class ^(plasma-changeicons)$"
      "move 999999 999999, match:class ^(plasma-changeicons)$"
      "move 40 80, match:title  ^(Copying — Dolphin)$"
      "tile 1, match:class ^dev\\.warp\\.Warp$"
      "float 1, match:title  ^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$"
      "keep_aspect_ratio 1, match:title  ^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$"
      "move 73% 72%, match:title  ^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$ "
      "size 25%, match:title  ^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$"
      "float 1, match:title  ^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$"
      "pin 1, match:title  ^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$"
      "immediate 1, match:title  .*\\.exe"
      "immediate 1, match:title  .*minecraft.*"
      "immediate 1, match:class ^(steam_app).*"
      "no_shadow 1, match:float no"
    ];
    workspace = [
      "special:special, gapsout:30"
    ];
    layerrule = [
      #"xray 1, .*"
      "no_anim 1, match:namespace walker"
      "no_anim 1,match:namespace selection"
      "no_anim 1,match:namespace overview"
      "no_anim 1,match:namespace anyrun"
      "no_anim 1,match:namespace indicator.*"
      "no_anim 1,match:namespace osk"
      "no_anim 1,match:namespace hyprpicker"
      "no_anim 1,match:namespace no_anim"
      "blur 1,match:namespace gtk-layer-shell"
      # "ignore_zero 1,match:namespace gtk-layer-shell"
      "blur 1,match:namespace launcher"
      "ignore_alpha 0.5,match:namespace launcher"
      "blur 1,match:namespace notifications"
      "ignore_alpha 0.69,match:namespace notifications"
      "blur 1,match:namespace logout_dialog # wlogout"
      "animation slide left,match:namespace sideleft.*"
      "animation slide right,match:namespace sideright.*"
      "blur 1,match:namespace session[0-9]*"
      "blur 1,match:namespace bar[0-9]*"
      "ignore_alpha 0.6,match:namespace bar[0-9]*"
      "blur 1,match:namespace barcorner.*"
      "ignore_alpha 0.6,match:namespace barcorner.*"
      "blur 1,match:namespace dock[0-9]*"
      "ignore_alpha 0.6,match:namespace dock[0-9]*"
      "blur 1,match:namespace indicator.*"
      "ignore_alpha 0.6,match:namespace indicator.*"
      "blur 1,match:namespace overview[0-9]*"
      "ignore_alpha 0.6,match:namespace overview[0-9]*"
      "blur 1,match:namespace cheatsheet[0-9]*"
      "ignore_alpha 0.6,match:namespace cheatsheet[0-9]*"
      "blur 1,match:namespace sideright[0-9]*"
      "ignore_alpha 0.6,match:namespace sideright[0-9]*"
      "blur 1,match:namespace sideleft[0-9]*"
      "ignore_alpha 0.6,match:namespace sideleft[0-9]*"
      "blur 1,match:namespace indicator.*"
      "ignore_alpha 0.6,match:namespace indicator.*"
      "blur 1,match:namespace osk[0-9]*"
      "ignore_alpha 0.6,match:namespace osk[0-9]*"
      "blur_popups 1,match:namespace quickshell:.*"
      "blur 1,match:namespace quickshell:.*"
      "ignore_alpha 0.79,match:namespace quickshell:.*"
      "animation slide,match:namespace quickshell:bar"
      "animation slide,match:namespace quickshell:verticalBar"
      "animation fade,match:namespace quickshell:screenCorners"
      "animation slide right,match:namespace quickshell:sidebarRight"
      "animation slide left,match:namespace quickshell:sidebarLeft"
      "animation slide top,match:namespace quickshell:wallpaperSelector"
      "animation slide bottom,match:namespace quickshell:osk"
      "animation slide bottom,match:namespace quickshell:dock"
      "animation slide bottom,match:namespace quickshell:cheatsheet"
      "blur 1,match:namespace quickshell:session"
      "no_anim 1,match:namespace quickshell:session"
      "ignore_alpha 0,match:namespace quickshell:session"
      "animation fade,match:namespace quickshell:notificationPopup"
      "blur 1,match:namespace quickshell:backgroundWidgets"
      "ignore_alpha 0.05,match:namespace quickshell:backgroundWidgets"
      "no_anim 1,match:namespace quickshell:screenshot"
      "animation popin 120%,match:namespace quickshell:screenCorners"
      "no_anim 1,match:namespace quickshell:lockWindowPusher"
      "no_anim 1,match:namespace quickshell:overview"
      "no_anim 1,match:namespace gtk4-layer-shell"
      "blur 1,match:namespace shell:bar"
      # "ignorezero,match:namespace shell:bar"
      "blur 1,match:namespace shell:notifications"
      "ignore_alpha 0.1,match:namespace shell:notifications"
      "blur 1,match:namespace vicinae"
      "ignore_alpha 0,match:namespace vicinae"
      "ignore_alpha 0,match:namespace wvkbd"
      "blur 1, ignore_alpha 0, match:namespace vicinae"
      "no_anim 1, match:namespace vicinae"
    ];
  };
}
