keys:
  - &home-laptop age179qajt8wkh9hav687evh79lkczdc97y5p2fpv0j7csyep4qkl3fsuzphp4
  - &master age1jy5gmxfrlyky2nu09rwan68vnp89vun8zmkeyg2e0cng3lc6ccyqdh9sd5
  - &office age1t24vpc9ejg393999sv0u7t0zzkjs94st9ktc36fltg69mssycccssg4698

creation_rules:
  - path_regex: secrets/personal\.yaml$
    key_groups:
      - age:
          - *home-laptop
          - *master
          - *office
  - path_regex: secrets/linkding-bookmarks\.html$
    input_type: binary
    key_groups:
      - age:
          - *home-laptop
          - *master
          - *office
