{
  imports = [
    ./opencode.nix
    ./claude.nix
    ./claude-resources
    ./claude-kit
    ./claude-launchers
    ./ruflo-cli.nix
    ./claude-flow-cli.nix
    ./ccr.nix
    ./ccmanager.nix
    ./claude-powerline.nix
    ./code-index.nix
    ./gitnexus-cli.nix
    ./jupyter-env-mcp.nix
    ./kindly-web-search.nix
    ./freshrss-mcp
    ./den
  ];
}
